Config = {}

Config.HashList = {
    Gunbelt     = 0x9B2C8B89,
    Mask        = 0x7505EF42,
    Holster     = 0xB6B6122D,
    Loadouts    = 0x83887E88,
    Coat        = 0xE06D30CE,
    Cloak       = 0x3C1A74CD,
    EyeWear     = 0x5E47CA6,
    Bracelet    = 0x7BC10759,
    Skirt       = 0xA0E3AB7F,
    Poncho      = 0xAF14310B,
    Spats       = 0x514ADCEA,
    NeckTies    = 0x7A96FACA,
    Spurs       = 0x18729F39,
    Pant        = 0x1D4C528A,
    Suspender   = 0x877A2CF7,
    Glove       = 0xEABE0032,
    Satchels    = 0x94504D26,
    GunbeltAccs = 0xF1542D11,
    CoatClosed  = 0x662AC34,
    Buckle      = 0xFAE9107F,
    RingRh      = 0x7A6BBD0B,
    Belt        = 0xA6D134C6,
    Accessories = 0x79D7DF96,
    Shirt       = 0x2026C46D,
    Gauntlets   = 0x91CE9B20,
    Chap        = 0x3107499B,
    NeckWear    = 0x5FC29285,
    Boots       = 0x777EC6EF,
    Vest        = 0x485EE834,
    RingLh      = 0xF16A1D23,
    Hat         = 0x9925C067,
    Dress       = 0xA2926F9B,
    Badge       = 0x3F7F3587,
    armor       = 0x72E6EF74,
    Hair        = 0x864B03AE,
    Beard       = 0xF8016BCA,
    bow         = 0x8E84A2AA,
}

Config.ClothItems = {
    clothtest = {
        disableitems = true,
        DisableClothes = {
            'Shirt',

        },
        pants = {
            name = 0xFFD41D69,
            albedo = 0xC266D5A3,
            normal = 0xB71451DE,
            material = 0x33E24AF5,
            palette = 0,
            tint0 = 255,
            tint1 = 255,
            tint2 = 255,
            wearablestate = 0,
            component = 0,
        },
        necktie_sapphire_pin = {
            name = 0xB10250E9,
            albedo = 0x97761002,
            normal = 0xF4435660,
            material = 0x3A18C320,
            palette = 0,
            tint0 = 255,
            tint1 = 255,
            tint2 = 255,
            wearablestate = 0,
            component = 0,
        },
        boots = {
            name = 0xD1589FAD,
            albedo = 0x7564D1C4,
            normal = 0x8342F98C,
            material = 0xB902FFA0,
            palette = 0,
            tint0 = 255,
            tint1 = 255,
            tint2 = 255,
            wearablestate = 0,
            component = 0,
        },
        coat = {
            name = joaat("cs_josiahtrelawny_ms1_coat_002"),
            albedo = 0x23C22FF5,
            normal = 0x15CFA26C,
            material = 0x46414BFE,
            palette = 0,
            tint0 = 255,
            tint1 = 255,
            tint2 = 255,
            wearablestate = 0,
            component = 0,
        },
        unknown = {
            name = 0xA4959DE2,
            albedo = 0x6F40C6F6,
            normal = 0x4A4E5F1F,
            material = 0x5D284219,
            palette = 0,
            tint0 = 0,
            tint1 = 0,
            tint2 = 0,
            wearablestate = 0,
            component = 0,
        },
        gloves = {
            name = 0xAB2CE480,
            albedo = 0x1A5CBE97,
            normal = 0x18EFB439,
            material = 0x0A8CE7B5,
            palette = 0,
            tint0 = 255,
            tint1 = 255,
            tint2 = 255,
            wearablestate = 0,
            component = 0,
        },
        hat = {
            name = 0x52E3E1BD,
            albedo = 0x59F21EB8,
            normal = 0xBA947493,
            material = 0x0EAFD475,
            palette = 0,
            tint0 = 255,
            tint1 = 255,
            tint2 = 255,
            wearablestate = 0,
            component = 0,
        },
        shirt = {
            name = 0xF03FA1A7,
            albedo = 0xFE677E55,
            normal = 0x3B2F5034,
            material = 0x70393527,
            palette = 0,
            tint0 = 255,
            tint1 = 255,
            tint2 = 255,
            wearablestate = 0,
            component = 0,
        },
        vest = {
            name = 0x8688EA2A,
            albedo = 0x2F63B623,
            normal = 0x685D78CE,
            material = 0x70C23488,
            palette = 0,
            tint0 = 255,
            tint1 = 255,
            tint2 = 255,
            wearablestate = 0,
            component = 0,
        },
    }, --- 

    northman = {
        disableitems = true,
        DisableClothes = {
            'Shirt',
            'Vest',
            'Dress',
            'Pant',
        },
        coat = {                         
            name = joaat("coat_mr1_029_duelwield"),
            albedo = 0xA2B97B52,
            normal = 0xA873E6CD,
            material = 0x3BAA787A,
            palette = 0xFB71527B,
            tint0 = 97,
            tint1 = 25,
            tint2 = 83,
            wearablestate = 0,
            component = 0, 
        },
        pants = {
            name = joaat ("pant_mr1_001"),
            albedo = joaat("pant_mr1_000_c1_997_ab"),
            normal = 0xF55A0C5A,
            material = 0x39395F3A,
            palette = 0x9AC34F34,
            tint0 = 201,
            tint1 = 143,
            tint2 = 21,
            wearablestate = 0,
            component = 0, 
        },
        glove = {
            name = joaat ("glov_mr1_007_under"),
            albedo = 0x0665677A,
            normal = 0x737AE58A,
            material = joaat ("glov_mr1_007_c3_000_m"),
            palette = 0xD1476963,
            tint0 = 14,
            tint1 = 14,
            tint2 = 14,
            wearablestate = 0,
            component = 0, 
        },

        boot = {
            name = joaat ("boot_mr1_072"),
            albedo = joaat ("boot_mr1_072_c1_999_ab"),
            normal = joaat("boot_mr1_072_c1_000_nm"),
            material = joaat ("boot_mr1_072_c1_000_m"),
            palette = 0xD1476963,
            tint0 = 0,
            tint1 = 0,
            tint2 = 0,
            wearablestate = 0,
            component = 0, 
        },
        vest = {
            name = joaat ("tie_mr1_030_vest"),
            albedo = 0x5702F857,
            normal = 0xE1906BC3,
            material = 0xFCA011BD,
            palette = 0x9AC34F34,
            tint0 = 21,
            tint1 = 27,
            tint2 = 12,
            wearablestate = 0,
            component = 0, 
        },
        belt = {
            name = joaat ("belt_mr1_002_holster_undercoat"),
            albedo = joaat ("belt_mr1_002_holster_c1_999_ab"),
            normal = 0x9E1482F8,
            material = 0x2B557148,
            palette = 0xD1476963,
            tint0 = 0,
            tint1 = 0,
            tint2 = 0,
            wearablestate = 0,
            component = 0, 
        },
        hat = {
            name = joaat ("hat_mr1_067"),
            albedo = 0xBD7405A5,
            normal = 0x14534508,
            material = 0x63B2CB82,
            palette = 0x4101ED87,
            tint0 = 254,
            tint1 = 241,
            tint2 = 242,
            wearablestate = 0,
            component = 0, 
        },
        mantle = {
            name = joaat ("mantle_mr1_000"),
            albedo = joaat ("mantle_mr1_000_c3_999_ab"),
            normal = joaat("mantle_mr1_000_c3_000_nm"),
            material = joaat ("mantle_mr1_000_c3_000_m"),
            palette = 0x9AC34F34,
            tint0 = 54,
            tint1 = 4,
            tint2 = 0,
            wearablestate = 0,
            component = 0, 
        },
        shirt = {
            name = 0x9B4F2708,
            albedo = 0x05BF68CB,
            normal = 0xFDBC1FA8,
            material = 0xBA1B72C4,
            palette = 0x357284BB,
            tint0 = 60,
            tint1 = 1,
            tint2 = 81,
            wearablestate = 0,
            component = 0, 
        },
    }, ---
    bankman = {
        disableitems = true,
        DisableClothes = {
            'Shirt',
            'Vest',
            

        },
        hat = {                          -- * just for organisation you can put any name
            name = joaat("hat_mr1_045"), -- can be a hash or a string ith a joaat
            albedo = 0xdf8e9968,
            normal = 0xfe7f8ea7,
            material = 0x15336f55,
            palette = 0xb562025c,
            tint0 = 49, -- these are the colors if you see another clothing that is the same you can use its colors and create different colors ith this hat for example you can have the color of the hat ith same as the coat
            tint1 = 38,
            tint2 = 38,
            wearablestate = 0,
            component = 0, -- any piece of clothing  add the hash here  of any hat for example
        },
        coat = {
            name = joaat("coat_mr1_049_alt01"),
            albedo = 0xbb33a570,
            normal = 0xd99124c7,
            material = 0x65873c60,
            palette = 0xaa65d8a3,
            tint0 = 49, -- these are the colors if you see another clothing that is the same you can use its colors and create different colors ith this hat for example you can have the color of the hat ith same as the coat
            tint1 = 38,
            tint2 = 38,
            wearablestate = 0,
            component = 0, -- any piece of clothing  add the hash here  of any hat for example
        },
        badge = {
            name = joaat("cs_mp_agent_hixon_ms1_badge_000"),
            albedo = joaat("cs_mp_agent_hixon_ms1_badge_000_c0_000_ab"),
            normal = joaat("cs_mp_agent_hixon_ms1_badge_000_c0_000_nm"),
            material = joaat("cs_mp_agent_hixon_ms1_badge_000_c0_000_m"),
            palette = 0xAA65D8A3,
            tint0 = 0,
            tint1 = 0,
            tint2 = 0,
            wearablestate = 0,
            component = 0,
        },
        glove = {
            name = joaat("glov_mr1_018"),
            albedo = 0xf3c8218f,
            normal = 0x618b0765,
            material = 0xf1fccee9,
            palette       = 0xf509c745,
            tint0         = 66,
            tint1         = 107,
            tint2         = 22,
            wearablestate = 0,
            component = 6, -- any piece of clothing  add the hash here  of any hat for example

        },

        belt = { -- army belt with no bag

            name          = joaat("belt_mr1_005"),
            albedo        = 0x0d44f5768,
            normal        = 0x7f7a454b,
            material      = 0xa94efba8,
            palette       = 0xf509c745,
            tint0         = 66,
            tint1         = 107,
            tint2         = 22,
            wearablestate = 0,
            component     = 7, -- any piece of clothing  add the hash here  of any hat for example

        },

    }, ---
    outfit_joud = {
        disableitems = false,
        DisableClothes = {
            'Shirt',
        },
        boots = {
            name = joaat("boot_fr1_000"),
            albedo = 0xD285B8A8,
            normal = 0x2EF3CD2A,
            material = 0x412CD379,
            palette = 0xF509C745,
            tint0 = 0,
            tint1 = 60,
            tint2 = 0,
            wearablestate = 0,
            component = 0,
        },
        hat = {
            name = joaat("hat_fr1_011"),
            albedo = 0x8C0EF49C,
            normal = 0x7A909B9C,
            material = 0x8B0C9DFA,
            palette = 0xFB71527B,
            tint0 = 24,
            tint1 = 28,
            tint2 = 28,
            wearablestate = 0,
            component = 0,
        },
        skirt = {
            name = joaat("lowr_fr1_013_elderlytattered"),
            albedo = joaat("lowr_fr1_013_c3_999_ab"),
            normal = 0x4CFF255D,
            material = 0xA26D1981,
            palette = 0xB9E7F722,
            tint0 = 21,
            tint1 = 21,
            tint2 = 21,
            wearablestate = 0,
            component = 0,
        },
        blouse = {
            name = joaat("uppr_fr1_046"),
            albedo = 0x42D52511,
            normal = 0x259B9B3F,
            material = 0x6928BA05,
            palette = 0x4101ED87,
            tint0 = 21,
            tint1 = 21,
            tint2 = 21,
            wearablestate = -152503185,
            component = 1218117202,
        },
        veil = {
            name = joaat("veil_fr1_000"),
            albedo = 0x87D5EDD9,
            normal = 0x156EF2C1,
            material = 0x1D92BA1B,
            palette = 0xFB71527B,
            tint0 = 95,
            tint1 = 43,
            tint2 = 105,
            wearablestate = 0,
            component = 0,
        },
    },
    militaryoutfitbrown = {              -- * ITEM NAME * --
        disableitems = false,
        DisableClothes = {
            'Shirt',
        },
        hat = {                          -- * just for organisation you can put any name
            name = joaat("hat_mr1_045"), -- can be a hash or a string ith a joaat
            albedo = 0xdf8e9968,
            normal = 0xfe7f8ea7,
            material = 0x15336f55,
            palette = 0xb562025c,
            tint0 = 49, -- these are the colors if you see another clothing that is the same you can use its colors and create different colors ith this hat for example you can have the color of the hat ith same as the coat
            tint1 = 38,
            tint2 = 38,
            wearablestate = 0,
            component = 0, -- any piece of clothing  add the hash here  of any hat for example
        },
        coat = {
            name = joaat("coat_mr1_049_alt01"),
            albedo = 0xbb33a570,
            normal = 0xd99124c7,
            material = 0x65873c60,
            palette = 0xaa65d8a3,
            tint0 = 49, -- these are the colors if you see another clothing that is the same you can use its colors and create different colors ith this hat for example you can have the color of the hat ith same as the coat
            tint1 = 38,
            tint2 = 38,
            wearablestate = 0,
            component = 0, -- any piece of clothing  add the hash here  of any hat for example
        },

        glove = {
            name = joaat("glov_mr1_018"),
            albedo = 0xf3c8218f,
            normal = 0x618b0765,
            material = 0xf1fccee9,
            palette = 0xaa65d8a3,
            tint0 = 0,
            tint1 = 0,
            tint2 = 0,
            wearablestate = 0,
            component = 6, -- any piece of clothing  add the hash here  of any hat for example

        },

        --[[     belt = { -- army belt with no bag

            name          = joaat("belt_mr1_005"),
            albedo        = 0x0d44f5768,
            normal        = 0x7f7a454b,
            material      = 0xa94efba8,
            palette       = 0xf509c745,
            tint0         = 66,
            tint1         = 107,
            tint2         = 22,
            wearablestate = 0,
            component     = 7, -- any piece of clothing  add the hash here  of any hat for example

        }, ]]

        bagbelt = {
            -- army bag with little bag
            name = joaat("accs_mr1_044_alt"),
            albedo = joaat("accs_mr1_044_c3_999_ab"),
            normal = 0x350ea195,
            material = 0xe17a5f2b,
            palette = joaat("metaped_tint_leather"),
            tint0 = 23,
            tint1 = 23,
            tint2 = 19,
            wearablestate = 0,
            component = 8, -- any piece of clothing  add the hash here  of any hat for example

        },

    },

    BeardMustache = {
        disableitems = false,
        DisableClothes = {
            'Shirt',
        },
        beard = {
            name = joaat("modular_beard_mr1_shv_stache_000_07"),
            albedo = 0xf8af92e5,
            normal = 0x7e6e8df9,
            material = 0xf4fd0d09,
            palette = 0xdfb1f64c,
            tint0 = 23,
            tint1 = 87,
            tint2 = 57,
            wearablestate = 0,
            component = 1,  -- any piece of clothing  add the hash here  of any hat for example
            isBeard = true, -- to remove beard to apply this one
        },
    },

    mailbag = {
        disableitems = false,
        DisableClothes = {
            'Shirt',
        },
        mailbag = {
            -- mail or an army bag
            name = joaat("accs_mr1_063_alt01"),
            albedo = 0x397dee7d,
            normal = 0xd3a89d94,
            material = 0xba734759,
            palette = 0xf509c745,
            tint0 = 93,
            tint1 = 10,
            tint2 = 63,
            wearablestate = 0,
            component = 8, -- any piece of clothing  add the hash here  of any hat for example
        },
    },

    militaryfrbag = {
        -- army food ration bag
        disableitems = false,
        DisableClothes = {
            'Shirt',
        },
        bag = {
            name = joaat("accs_mr1_062_alt01"),
            albedo = joaat("accs_mr1_062_c3_001_ab"),
            normal = 0x348b7ca3,
            material = 0x8e0b712a,
            palette = joaat("metaped_tint_leather"),
            tint0 = 124,
            tint1 = 58,
            tint2 = 48,
            wearablestate = 1516878518,
            component = 8, -- any piece of clothing  add the hash here  of any hat for example


        }
    },

    johnmarshtonoutfit = {
        disableitems = false,
        DisableClothes = {
            'Shirt',
        },
        -- john marshton outfit
        hat = {
            name = 0xe2527c43,
            albedo = 0xc81e8ac9,
            normal = 0xe00591b3,
            material = 0x17f2ae81,
            palette = 0,
            tint0 = 0,
            tint1 = 0,
            tint2 = 0,
            wearablestate = 0,
            component = 0,
            -- any piece of clothing  add the hash here  of any hat for example
        },

        pants = {
            name = joaat("player_three_ms1_pants_002_med"),
            albedo = 0xc7b2cc00,
            normal = 0x72c8ec18,
            material = 0x0337d995,
            palette = 0,
            tint0 = 0,
            tint1 = 0,
            tint2 = 0,
            wearablestate = -421745099,
            component = -2068143351,

        },

        shirt = {
            name = 0xb313e3e6,
            albedo = 0x46ddb7fa,
            normal = 0xd10748fb,
            material = 0xfa910fea,
            palette = 0,
            tint0 = 0,
            tint1 = 0,
            tint2 = 0,
            wearablestate = -956779256,
            component = 543187419,
        },

        boot = {
            name = joaat("player_three_ms1_boot_000_full"),
            albedo = 0xab593f8c,
            normal = 0x3c4dae77,
            material = 0x95dfc489,
            palette = 0,
            tint0 = 0,
            tint1 = 0,
            tint2 = 0,
            wearablestate = -421745099,
            component = -2068143351,
        },

        suspenders = {
            name = joaat("player_three_ms1_suspenders_000_full"),
            albedo = 0xdb2a6333,
            normal = 0x0bed40fb,
            material = 0x63aa4c61,
            palette = 0,
            tint0 = 0,
            tint1 = 0,
            tint2 = 0,
            wearablestate = 0,
            component = 0,

        },

        belt = {
            name = 0x2a8642ac,
            albedo = 0xc6d5bdf0,
            normal = 0xb4eb3c32,
            material = 0x6df7b306,
            palette = 0,
            tint0 = 0,
            tint1 = 0,
            tint2 = 0,
            wearablestate = 0,
            component = 0,
        },

    },
    -- fussarDicta = {
    --     disableitems = false,
    --     DisableClothes = {
    --         'Shirt',
    --     },
    --     coat = {
    --         name = 0xC41E7E33,
    --         albedo = joaat("cs_fussar_ms1_coat_001_c0_000_ab"),
    --         normal = joaat("cs_fussar_ms1_coat_001_c0_000_nm"),
    --         material = 0xD2042887,
    --         palette = 0,
    --         tint0 = 0,
    --         tint1 = 0,
    --         tint2 = 0,
    --         wearablestate = 553332713,
    --         component = 1180660122, -- any piece of clothing  add the hash here  of any hat for example
    --     },

    --     glove = {
    --         name = 0xB0F8A6B8,
    --         albedo = 0xF1E67549,
    --         normal = joaat("glov_mr1_018_c1_000_nm"),
    --         material = 0xDF527001,
    --         palette = 0xAA65D8A3,
    --         tint0 = 16,
    --         tint1 = 49,
    --         tint2 = 80,
    --         wearablestate = -1248641218,
    --         component = 543187419, -- any piece of clothing  add the hash here  of any hat for example

    --     },
    --     sword = {
    --         name = 0x470EE386,
    --         albedo = joaat("cs_fussar_ms1_sword_000_c0_000_ab"),
    --         normal = joaat("cs_fussar_ms1_sword_000_c0_000_nm"),
    --         material = 0xE4225130,
    --         palette = 0,
    --         tint0 = 0,
    --         tint1 = 0,
    --         tint2 = 0,
    --         wearablestate = 0,
    --         component = 0,-- any piece of clothing  add the hash here  of any hat for example

    --     },
    --     accesories = {
    --         name = 0x6BD1B210,
    --         albedo = joaat("cs_fussar_ms1_accessories_001_c0_000_ab"),
    --         normal = joaat("cs_fussar_ms1_accessories_001_c0_000_nm"),
    --         material = 0xD8338792,
    --         palette = 0xAA65D8A3,
    --         tint0 = 0,
    --         tint1 = 0,
    --         tint2 = 0,
    --         wearablestate = 0,
    --         component = 0,-- any piece of clothing  add the hash here  of any hat for example

    --     },
    --     boot = {
    --         name = 0xD6DB469A,
    --         albedo = joaat("cs_fussar_ms1_boot_001_c0_000_ab"),
    --         normal = joaat("cs_fussar_ms1_boot_001_c0_000_nm"),
    --         material = 0xF615D429,
    --         palette = 0,
    --         tint0 = 0,
    --         tint1 = 0,
    --         tint2 = 0,
    --         wearablestate = 0,
    --         component = 0,
    --     },
    --     pant = {
    --         name = 0xAAD66B83,
    --         albedo = joaat("cs_fussar_ms1_pants_001_c0_000_ab"),
    --         normal = joaat("cs_fussar_ms1_pants_001_c0_000_nm"),
    --         material = 0x90789A77,
    --         palette = 0,
    --         tint0 = 0,
    --         tint1 = 0,
    --         tint2 = 0,
    --         wearablestate = -395059020,
    --         component = -2068143351,
    --     },
    -- },
    fussarDicta = {
        disableitems = false,
        DisableClothes = {
            'Shirt',
            'Vest',
            'hat',
            'glove',
        },
        coat = { -- معطف 
            name = 0xC41E7E33,
            albedo = joaat("cs_fussar_ms1_coat_001_c0_000_ab"),
            normal = joaat("cs_fussar_ms1_coat_001_c0_000_nm"),
            material = 0xD2042887,
            palette = 0,
            tint0 = 0,
            tint1 = 0,
            tint2 = 0,
            wearablestate = 553332713,
            component = 1180660122, -- any piece of clothing  add the hash here  of any hat for example
        },
        glove = { -- قفازات
            name = 0xB0F8A6B8,
            albedo = 0xF1E67549,
            normal = joaat("glov_mr1_018_c1_000_nm"),
            material = 0xDF527001,
            palette = 0xAA65D8A3,
            tint0 = 16,
            tint1 = 49,
            tint2 = 80,
            wearablestate = -1248641218,
            component = 543187419, -- any piece of clothing  add the hash here  of any hat for example

        },
        sword = { --سيف
            name = 0x470EE386,
            albedo = joaat("cs_fussar_ms1_sword_000_c0_000_ab"),
            normal = joaat("cs_fussar_ms1_sword_000_c0_000_nm"),
            material = 0xE4225130,
            palette = 0,
            tint0 = 0,
            tint1 = 0,
            tint2 = 0,
            wearablestate = 0,
            component = 0,-- any piece of clothing  add the hash here  of any hat for example
        },
        accesories = { --مُكَمِّلات
            name = 0x6BD1B210,
            albedo = joaat("cs_fussar_ms1_accessories_001_c0_000_ab"),
            normal = joaat("cs_fussar_ms1_accessories_001_c0_000_nm"),
            material = 0xD8338792,
            palette = 0xAA65D8A3,
            tint0 = 0,
            tint1 = 0,
            tint2 = 0,
            wearablestate = 0,
            component = 0,-- any piece of clothing  add the hash here  of any hat for example
        },
        boot = {  -- حذاء طويل
            name = 0xD6DB469A,
            albedo = joaat("cs_fussar_ms1_boot_001_c0_000_ab"),
            normal = joaat("cs_fussar_ms1_boot_001_c0_000_nm"),
            material = 0xF615D429,
            palette = 0,
            tint0 = 0,
            tint1 = 0,
            tint2 = 0,
            wearablestate = 0,
            component = 0,
        },
        pant = {  -- بنطال
            name = 0xAAD66B83,
            albedo = joaat("cs_fussar_ms1_pants_001_c0_000_ab"),
            normal = joaat("cs_fussar_ms1_pants_001_c0_000_nm"),
            material = 0x90789A77,
            palette = 0,
            tint0 = 0,
            tint1 = 0,
            tint2 = 0,
            wearablestate = -395059020,
            component = -2068143351,
        },
    },
    policeBWoutfit = {
        disableitems = false,
        DisableClothes = {
            'Shirt',
        },
        hat = {
            name = joaat("hat_mr1_059"),
            albedo = 0xf0b94771,
            normal = 0xdcef8989,
            material = 0x30c312f6,
            palette = 0xfb71527b,
            tint0 = 23,
            tint1 = 24,
            tint2 = 24,
            wearablestate = 0,
            component = 0, -- any piece of clothing  add the hash here  of any hat for example
        },
        coat = {
            name = joaat("combocoat_mr1_058"),
            albedo = 0x2aac56a6,
            normal = 0x58e86189,
            material = 0x19187ab4,
            palette = 0xaa65d8a3,
            tint0 = 0,
            tint1 = 0,
            tint2 = 0,
            wearablestate = -130653580,
            component = 543187419, -- any piece of clothing  add the hash here  of any hat for example
        },

        gloves = {
            name = joaat("glov_mr1_015_under"),
            albedo = joaat("glov_mr1_015_c1_999_ab"),
            normal = 0x8a17bdf2,
            material = 0xb8c5a596,
            palette = 0xfb71527b,
            tint0 = 0,
            tint1 = 0,
            tint2 = 0,
            wearablestate = -130653580,
            component = 543187419, -- any piece of clothing  add the hash here  of any hat for example
        },

        pantbootscombo = {
            name = joaat("tuxlower_mr1_000"),
            albedo = 0x7dea5751,
            normal = 0x2921a026,
            material = 0x6d91946f,
            palette = 0xf509c745,
            tint0 = 0,
            tint1 = 1,
            tint2 = 3,
            wearablestate = -395059020,
            component = -2068143351,
        },
    },
    -- police black hat
    SDpolicehatMale = {
        disableitems = false,
        DisableClothes = {
            'Shirt',
        },
        hat = {
            name = joaat("hat_mr1_139"),
            albedo = 0xada80c1c,
            normal = 0xeb963573,
            material = 0xa475e28c,
            palette = 0xfb71527b,
            tint0 = 21,
            tint1 = 34,
            tint2 = 241,
            wearablestate = 0,
            component = 0, -- any piece of clothing  add the hash here  of any hat for example
        },
    },

    -- police outfit gey 2
    policeOutfitDispatch = {
        disableitems = false,
        DisableClothes = {
            'Shirt',
        },
        coat = {
            name = joaat("combocoat_mr1_056"),
            albedo = 0xcfd4a033,
            normal = 0x686880b0,
            material = 0x7f0e732d,
            palette = 0xfb71527b,
            tint0 = 15,
            tint1 = 16,
            tint2 = 15,
            wearablestate = -130653580,
            component = 543187419, -- any piece of clothing  add the hash here  of any hat for example
        },
        hat = {
            name = joaat("hat_mr1_059"),
            albedo = 0xf0b94771,
            normal = 0xdcef8989,
            material = 0x30c312f6,
            palette = 0xfb71527b,
            tint0 = 23,
            tint1 = 24,
            tint2 = 24,
            wearablestate = 0,
            component = 0, -- any piece of clothing  add the hash here  of any hat for example
        },
        glove = {
            name = joaat("glov_mr1_021"),
            albedo = joaat("glov_mr1_021_c1_999_ab"),
            normal = 0x19ab96fa,
            material = 0xcb4d4365,
            palette = 0xaa65d8a3,
            tint0 = 0,
            tint1 = 72,
            tint2 = 73,
            wearablestate = -130653580,
            component = 543187419, -- any piece of clothing  add the hash here  of any hat for example

        },
        pantbootscombo = {
            name = joaat("tuxlower_mr1_000"),
            albedo = 0x7dea5751,
            normal = 0x2921a026,
            material = 0x6d91946f,
            palette = 0xf509c745,
            tint0 = 0,
            tint1 = 1,
            tint2 = 3,
            wearablestate = -395059020,
            component = -2068143351,
        },
    },

    -- police outfit blue
    bluepoliceoutfit = {
        disableitems = false,
        DisableClothes = {
            'Shirt',
        },
        hat = {
            name = joaat("hat_mr1_059"),
            albedo = 0xf0b94771,
            normal = 0xdcef8989,
            material = 0x30c312f6,
            palette = 0x63838a81,
            tint0 = 139,
            tint1 = 254,
            tint2 = 143,
            wearablestate = 0,
            component = 0, -- any piece of clothing  add the hash here  of any hat for example
        },
        glove = {
            name = joaat("glov_mr1_021"),
            albedo = joaat("glov_mr1_021_c1_999_ab"),
            normal = 0x8a17bdf2,
            material = 0xb8c5a596,
            palette = 0xfb71527b,
            tint0 = 0,
            tint1 = 0,
            tint2 = 0,
            wearablestate = -130653580,
            component = 543187419, -- any piece of clothing  add the hash here  of any hat for example
        },
        coat = {
            name = joaat("combocoat_mr1_058"),
            albedo = 0x7f39b31a,
            normal = 0xfa139d24,
            material = 0x68e6f1d5,
            palette = 0xfb71527b,
            tint0 = 0,
            tint1 = 0,
            tint2 = 0,
            wearablestate = -130653580,
            component = 543187419, -- any piece of clothing  add the hash here  of any hat for example
        },
        pantbootscombo = {
            name = joaat("tuxlower_mr1_000"),
            albedo = 0x7dea5751,
            normal = 0x2921a026,
            material = 0x6d91946f,
            palette = 0xf509c745,
            tint0 = 0,
            tint1 = 1,
            tint2 = 3,
            wearablestate = -395059020,
            component = -2068143351,
        },
    },

    TrainConductorOutfit = {
        disableitems = false,
        DisableClothes = {
            'Shirt',
        },
        coat = {
            name = joaat("combocoat_mr1_015"),
            albedo = joaat("combocoat_mr1_015_c1_999_ab"),
            normal = 0xce7e7b62,
            material = 0xe9c9358f,
            palette = joaat("metaped_tint_generic_clean"),
            tint0 = 143,
            tint1 = 15,
            tint2 = 142,
            wearablestate = -1248641218,
            component = 543187419,
        },

        hat = {
            name = joaat("hat_mr1_026"),
            albedo = 0x9fa8c0fb,
            normal = 0x772638bd,
            material = 0x542fcd2f,
            palette = 0x3385c5db,
            tint0 = 142,
            tint1 = 142,
            tint2 = 40,
            wearablestate = 255,
        },

        glove = {
            name = joaat("glov_mr1_021"),
            albedo = joaat("glov_mr1_021_c1_999_ab"),
            normal = 0x8a17bdf2,
            material = 0xb8c5a596,
            palette = 0xfb71527b,
            tint0 = 0,
            tint1 = 0,
            tint2 = 0,
            wearablestate = -1248641218,
            component = 543187419,
        },

        tie = {
            name = joaat("tie_mr1_024_vest_alt"),
            albedo = 0x999ddb7b,
            normal = 0x6e18b6d9,
            material = 0x9e0e0e0e,
            palette = joaat("metaped_tint_generic_clean"),
            tint0 = 21,
            tint1 = 21,
            tint2 = 21,
            wearablestate = 0,
        }
    },

    nativeoutfit = {
        disableitems = true,
        DisableClothes = {
            'Shirt',
        },
        pants = {
            name          = 0xa01796c0,
            albedo        = 0x5549c7ab,
            normal        = 0x98f8376f,
            material      = 0x26e86440,
            palette       = 0x00000,
            tint0         = 0,
            tint1         = 0,
            tint2         = 0,
            wearablestate = -421745099,
            component     = -2068143351
        },

        boots = {
            name          = 0xb42d34c1,
            albedo        = 0x85789bfc,
            normal        = 0x2b4996c3,
            material      = 0x2e4fd21a,
            palette       = 0x00000,
            tint0         = 0,
            tint1         = 0,
            tint2         = 0,
            wearablestate = -421745099,
            component     = -2068143351
        },
        accesorie = {
            name = 0x89609252,
            albedo = 0xa5e82f85,
            normal = 0x9bdd1fbf,
            material = 0x6c5a484f,
            palette = 0xaa65d8a3,
            tint0 = 9,
            tint1 = 3,
            tint2 = 3,
            wearablestate = 255,
            component = 0,
        },


        neckless = {
            name = 0xf7bb1424,
            albedo = 0x27760d9b,
            normal = 0x6177d502,
            material = 0x1ffe1ba1,
            palette = 0x00000,
            tint0 = 0,
            tint1 = 0,
            tint2 = 0,
            wearablestate = 255,
            component = 0,
        },
        coat = {
            name = 0x77ba8f12,
            albedo = 0xdee67011,
            normal = 0xeb0d1ba6,
            material = 0x8809976c,
            palette = 0x00000,
            tint0 = 0,
            tint1 = 0,
            tint2 = 0,
            wearablestate = 255,
            component = 0,
        },

        f = {
            name = 0x96127848,
            albedo = 0x332a2553,
            normal = 0xcdfcce7f,
            material = 0x6a95e633,
            palette = 0x00000,
            tint0 = 0,
            tint1 = 0,
            tint2 = 0,
            wearablestate = 255,
            component = 0,
        },

        nativebag = {
            name = 0xd7798e00,
            albedo = 0x506480f1,
            normal = 0xe068c182,
            material = 0xaf115328,
            palette = 0x00000,
            tint0 = 0,
            tint1 = 0,
            tint2 = 0,
            wearablestate = 255,
            component = 0,
        },
        ss = {
            name = 0x5b5b0b79,
            albedo = 0xdfae0c05,
            normal = joaat("hand_mr1_000_c0_000_nm"),
            material = 0x6b504bec,
            palette = 0x00000,
            tint0 = 0,
            tint1 = 0,
            tint2 = 0,
            wearablestate = 255,
            component = 0,
        },

    },
    
    watert = { -- Parte do pncho
        disableitems = true,
        DisableClothes = {
            'Shirt',
        },
        manto = {
            name = joaat("uppr_mr1_137_belt"),
            albedo = 0x4E77B791,
            normal = 0x4FEFB88E,
            material = 0x816D410E,
            palette = 0x4101ED87,
            tint0 = 254,
            tint1 = 253,
            tint2 = 241,
            wearablestate = 0,
            component = 0, -- any piece of clothing  add the hash here  of any hat for example
        },
        manto2 = {
            name = joaat("uppertorso_mr1_001"),
            albedo = 0xDFAE0C05,
            normal = joaat("hand_mr1_000_c0_000_nm"),
            material = 0x6B504BEC,
            palette = 0xAA65D8A3,
            tint0 = 0,
            tint1 = 0,
            tint2 = 0,
            wearablestate = 0,
            component = 0, -- any piece of clothing  add the hash here  of any hat for example
        },
        belt = {
            name = joaat("belt_mr1_009"),
            albedo = 0xF3F755FE,
            normal = 0x33505C2A,
            material = 0x1694D6CC,
            palette = 0x4101ED87,
            tint0 = 15,
            tint1 = 8,
            tint2 = 41,
            wearablestate = 0,
            component = 0, -- any piece of clothing  add the hash here  of any hat for example
        },
        calcas = {
            name = joaat("pantcombo_mr1_001"),
            albedo = joaat("pantcombo_mr1_001_c1_999_ab"),
            normal = 0xE6922DBF,
            material = 0x158B0635,
            palette = 0x4101ED87,
            tint0 = 254,
            tint1 = 241,
            tint2 = 244,
            wearablestate = 0,
            component = 0, -- any piece of clothing  add the hash here  of any hat for example
        },
    },
    
    dutchfits = { --- itemsname
        disableitems = false,
        DisableClothes = {
            'Shirt',
        },
        coatdutch = {
            name = joaat("mp_coat_mr1_405") ,
            albedo = joaat("mp_coat_mr1_405_c1_000_ab"),
            normal = joaat("mp_coat_mr1_405_c1_000_nm"),
            material = joaat("mp_coat_mr1_405_c1_000_m"),
            palette =0,
            tint0 = 0,
            tint1 = 0,
            tint2 = 0,
            wearablestate = 0,
            component = 0,
        },
        hat = {
            name = joaat("mp_hat_mr1_407") ,
            albedo = joaat("mp_hat_mr1_407_c1_000_ab"),
            normal = joaat("mp_hat_mr1_407_c1_000_nm"),
            material = joaat("mp_hat_mr1_407_c1_000_m"),
            palette = 0,
            tint0 = 0,
            tint1 = 0,
            tint2 = 0,
            wearablestate = 0,
            component = 0,
        },
        vest = {
            name = joaat("mp_vest_mr1_400") ,
            albedo = joaat("mp_vest_mr1_400_c1_000_ab"),
            normal = joaat("mp_vest_mr1_400_c1_000_nm"),
            material = joaat("mp_vest_mr1_400_c1_000_m"),
            palette = 0,
            tint0 = 0,
            tint1 = 0,
            tint2 = 0,
            wearablestate = 0,
            component = 0,
        },
        rings = {
            name = joaat("mp_ringr_mr1_400") ,
            albedo = joaat("mp_ringr_mr1_400_c1_000_ab"),
            normal = joaat("mp_ringr_mr1_400_c1_000_nm"),
            material = joaat("mp_ringr_mr1_400_c1_000_m"),
            palette = 0,
            tint0 = 0,
            tint1 = 0,
            tint2 = 0,
            wearablestate = 0,
            component = 0,
        },
        shirt = {
            name = joaat("mp_shirts_full_mr1_401") ,
            albedo = joaat("mp_shirts_mr1_401_c1_000_ab"),
            normal = joaat("mp_shirts_mr1_401_c1_000_nm"),
            material = joaat("mp_shirts_mr1_401_c1_000_m"),
            palette = 0,
            tint0 = 0,
            tint1 = 0,
            tint2 = 0,
            wearablestate = 0,
            component = 0,
        },
        pants = {
            name = joaat("mp_pants_mr1_401") ,
            albedo = joaat("mp_pants_mr1_401_c1_000_ab"),
            normal = joaat("mp_pants_mr1_401_c1_000_nm"),
            material = joaat("mp_pants_mr1_401_c1_000_m"),
            palette = 0,
            tint0 = 0,
            tint1 = 0,
            tint2 = 0,
            wearablestate = 0,
            component = 0,
        },
        boots = {
            name = joaat("mp_boots_mr1_400") ,
            albedo = joaat("mp_boots_mr1_400_c1_000_ab"),
            normal = joaat("mp_boots_mr1_400_c1_000_nm"),
            material = joaat("mp_boots_mr1_400_c1_000_m"),
            palette = 0,
            tint0 = 0,
            tint1 = 0,
            tint2 = 0,
            wearablestate = 0,
            component = 0,
        },
        spurs = {
            name = joaat("mp_spurs_mr1_400") ,
            albedo = joaat("mp_spurs_mr1_400_c1_000_ab"),
            normal = joaat("mp_spurs_mr1_400_c1_000_nm"),
            material = joaat("mp_spurs_mr1_400_c1_000_m"),
            palette = 0,
            tint0 = 0,
            tint1 = 0,
            tint2 = 0,
            wearablestate = 0,
            component = 0,
        },
        belt = {
            name = 0xAADD010B,
            albedo = joaat("cs_francis_sinclair_ms1_belt_000_c0_000_ab"),
            normal = joaat("cs_francis_sinclair_ms1_belt_000_c0_000_nm"),
            material = 0x67D104FF,
            palette = 0,
            tint0 = 0,
            tint1 = 0,
            tint2 = 0,
            wearablestate = 0,
            component = 0,
        },

    },

    hanshal = {
        disableitems = false,
        DisableClothes = {
            'Shirt',
            'Vest',
            'Dress',
            'Pant',
        },
        vest = {                         
            name = joaat("mp_cultist_vest_mr1_000"),
            albedo = joaat("mp_cultist_vest_mr1_000_c1_999_ab"),
            normal = joaat("mp_cultist_vest_mr1_000_c1_999_nm"),
            material = joaat("mp_cultist_vest_mr1_000_c1_999_m"),
            palette = 0xF93DB0C8,
            tint0 = 17,
            tint1 = 243,
            tint2 = 62,
            wearablestate = 0,
            component = 0, 
        },
        pants = {
            name = joaat ("mp_pant_mr1_071_cultist"),
            albedo = joaat("mp_pant_mr1_071_c1_999_ab"),
            normal = joaat("mp_pant_mr1_071_c1_000_nm"),
            material = joaat("mp_pant_mr1_071_c1_000_m"),
            palette = 0x3F6E70FF,
            tint0 = 0,
            tint1 = 0,
            tint2 = 0,
            wearablestate = 0,
            component = 0, 
        },
        boot = {
            name = joaat ("boot_mr1_073"),
            albedo = 0xAA0E81FA,
            normal = 0x4DEFFC6A,
            material = 0x723B06C2,
            palette = 0xF93DB0C8,
            tint0 = 0,
            tint1 = 0,
            tint2 = 0,
            wearablestate = 0,
            component = 0, 
        },

        uppertorso = {
            name = joaat ("uppertorso_mr1_001"),
            albedo = 0xDFAE0C05,
            normal = joaat("hand_mr1_000_c0_000_nm"),
            material = 0x6B504BEC,
            palette = 0x9AC34F34,
            tint0 = 0,
            tint1 = 0,
            tint2 = 0,
            wearablestate = 0,
            component = 0, 
        },
        lowertorso = {
            name = joaat ("lowertorso_mr1_004"),
            albedo = joaat ("feet_mr1_000_c0_008_ab"),
            normal = joaat("feet_mr1_000_c0_000_nm"),
            material = joaat ("feet_mr1_000_c0_011_m"),
            palette = 0x9AC34F34,
            tint0 = 21,
            tint1 = 21,
            tint2 = 21,
            wearablestate = 0,
            component = 0, 
        },
        robe = {
            name = joaat ("mp_cultist_robe_mr1_002_r_vest"),
            albedo = joaat ("mp_cultist_robe_mr1_001_c1_999_ab"),
            normal = joaat("mp_cultist_robe_mr1_001_c1_000_nm"),
            material = joaat ("mp_cultist_robe_mr1_001_c1_000_m"),
            palette = 0x3F6E70FF,
            tint0 = 0,
            tint1 = 0,
            tint2 = 0,
            wearablestate = 0,
            component = 0, 
        },

        gauntlets = {
            name = joaat ("mp_cultist_gauntlets_mr1_000_full"),
            albedo = joaat ("mp_cultist_gauntlets_mr1_000_full_c1_999_ab"),
            normal = joaat("mp_cultist_gauntlets_mr1_000_full_c1_999_nm"),
            material = joaat ("mp_cultist_gauntlets_mr1_000_full_c1_999_m"),
            palette = 0xF93DB0C8,
            tint0 = 17,
            tint1 = 243,
            tint2 = 62,
            wearablestate = 0,
            component = 0, 
        },
        helmet = {
            name = joaat ("mp_helmet_mr1_002_full"),
            albedo = joaat ("mp_helmet_mr1_002_full_c1_999_ab"),
            normal = joaat("mp_helmet_mr1_002_full_c1_001_nm"),
            material = joaat ("mp_helmet_mr1_002_full_c1_001_m"),
            palette = 0xF93DB0C8,
            tint0 = 17,
            tint1 = 17,
            tint2 = 62,
            wearablestate = 0,
            component = 0, 
        },
    }, ---

    saher = {
        disableitems = false,
        DisableClothes = {
            'Shirt',
            'Vest',
            'Dress',
            'Pant',
        },
        vest = {                         
            name = joaat("mp_cultist_vest_mr1_000"),
            albedo = joaat("mp_cultist_vest_mr1_000_c1_999_ab"),
            normal = joaat("mp_cultist_vest_mr1_000_c1_999_nm"),
            material = joaat("mp_cultist_vest_mr1_000_c1_999_m"),
            palette = 0xF93DB0C8,
            tint0 = 246,
            tint1 = 253,
            tint2 = 60,
            wearablestate = 0,
            component = 0, 
        },
        pants = {
            name = joaat ("mp_pant_mr1_071_cultist"),
            albedo = joaat("mp_pant_mr1_071_c1_999_ab"),
            normal = joaat("mp_pant_mr1_071_c1_000_nm"),
            material = joaat("mp_pant_mr1_071_c1_000_m"),
            palette = 0xF93DB0C8,
            tint0 = 16,
            tint1 = 1,
            tint2 = 2,
            wearablestate = 0,
            component = 0, 
        },
        boot = {
            name = joaat ("boot_mr1_073"),
            albedo = 0xAA0E81FA,
            normal = 0x4DEFFC6A,
            material = 0x723B06C2,
            palette = 0xF93DB0C8,
            tint0 = 0,
            tint1 = 0,
            tint2 = 0,
            wearablestate = 0,
            component = 0, 
        },
        uppertorso = {
            name = joaat ("uppertorso_mr1_001"),
            albedo = 0xDFAE0C05,
            normal = joaat("hand_mr1_000_c0_000_nm"),
            material = 0x6B504BEC,
            palette = 0x9AC34F34,
            tint0 = 0,
            tint1 = 0,
            tint2 = 0,
            wearablestate = 0,
            component = 0, 
        },
        lowertorso = {
            name = joaat ("lowertorso_mr1_004"),
            albedo = joaat ("feet_mr1_000_c0_008_ab"),
            normal = joaat("feet_mr1_000_c0_000_nm"),
            material = joaat ("feet_mr1_000_c0_011_m"),
            palette = 0x9AC34F34,
            tint0 = 28,
            tint1 = 28,
            tint2 = 28,
            wearablestate = 0,
            component = 0, 
        },
        robe = {
            name = joaat ("mp_cultist_robe_mr1_002_r_vest"),
            albedo = joaat ("mp_cultist_robe_mr1_001_c1_999_ab"),
            normal = joaat("mp_cultist_robe_mr1_001_c1_000_nm"),
            material = joaat ("mp_cultist_robe_mr1_001_c1_000_m"),
            palette = 0x4101ED87,
            tint0 = 121,
            tint1 = 119,
            tint2 = 120,
            wearablestate = 0,
            component = 0, 
        },
        cultist = {
            name = joaat ("mp_cultist_vest_mr1_000"),
            albedo = joaat ("mp_cultist_vest_mr1_000_c1_999_ab"),
            normal = joaat("mp_cultist_vest_mr1_000_c1_999_nm"),
            material = joaat ("mp_cultist_vest_mr1_000_c1_999_m"),
            palette = 0xF93DB0C8,
            tint0 = 246,
            tint1 = 253,
            tint2 = 60,
            wearablestate = 0,
            component = 0, 
        },
        gauntlets = {
            name = joaat ("mp_cultist_gauntlets_mr1_000_full"),
            albedo = joaat ("mp_cultist_gauntlets_mr1_000_full_c1_999_ab"),
            normal = joaat("mp_cultist_gauntlets_mr1_000_full_c1_999_nm"),
            material = joaat ("mp_cultist_gauntlets_mr1_000_full_c1_999_m"),
            palette = 0x4101ED87,
            tint0 = 247,
            tint1 = 254,
            tint2 = 246,
            wearablestate = 0,
            component = 0, 
        },
    }, ---
 
}


    