
QBattlepass = {}

QBattlepass.PremiumPrice = 200

QBattlepass.ImageLocation = "nui://vorp_inventory/html/img/items/"

QBattlepass.FreeItems = {
    [1] = {
        itemname = 'whisky',
        label = 'whisky',
        image = 'whisky.png',
        count = 10, 
        category = 'item',
    },
    [2] = {
        itemname = 'wine',
        label = 'wine',
        image = 'wine.png',
        count = 10, 
        category = 'item',
    },
    [3] = {
        itemname = 'consumable_apple',
        label = 'consumable_apple',
        image = 'consumable_apple.png',
        count = 10, 
        category = 'item',
    },
    [4] = {
        itemname = 'beer',
        label = 'beer',
        image = 'beer.png',
        count = 10, 
        category = 'item',
    },
    [5] = {
        itemname = 'wood',
        label = 'wood',
        image = 'wood.png',
        count = 5, 
        category = 'item',
    },
    [6] = {
        itemname = 'ammoarrownormal',
        label = 'ammoarrownormal',
        image = 'ammoarrownormal.png',
        count = 5, 
        category = 'item',
    },
    [7] = {
        itemname = 'consumable_salmon',
        label = 'consumable_salmon',
        image = 'consumable_salmon.png',
        count = 10, 
        category = 'item',
    },
    [8] = {
        itemname = 'shove1',
        label = 'shove1',
        image = 'shove1.png',
        count = 1, 
        category = 'item',
    },
    [9] = {
        itemname = 'consumable_kidneybeans',
        label = 'consumable_kidneybeans',
        image = 'consumable_kidneybeans.png',
        count = 10, 
        category = 'item',
    },
    [10] = {
        itemname = 'lighter',
        label = 'lighter',
        image = 'lighter.png',
        count = 3, 
        category = 'item',
    },
    [11] = {
        itemname = 'consumable_water',
        label = 'consumable_water',
        image = 'consumable_water.png',
        count = 10, 
        category = 'item',
    },
    [12] = {
        itemname = 'goldbar',
        label = 'goldbar',
        image = 'goldbar.png',
        count = 3, 
        category = 'item',
    },
    [13] = {
        itemname = 'irobar',
        label = 'irobar',
        image = 'irobar.png',
        count = 10, 
        category = 'item',
    },
    [14] = {
        itemname = 'consumable_apple',
        label = 'consumable_apple',
        image = 'consumable_apple.png',
        count = 10, 
        category = 'item',
    },
}



QBattlepass.PremiumItems = {
    [1] = {
        itemname = 'moonshine',
        label = 'moonshine',
        image = 'moonshine.png',
        count = 10, 
        category = 'item',
    },
    [2] = {
        itemname = 'whisky',
        label = 'whisky',
        image = 'whisky.png',
        count = 10, 
        category = 'item',
    },
    [3] = {
        itemname = 'wine',
        label = 'wine',
        image = 'wine.png',
        count = 10, 
        category = 'item',
    },
    [4] = {
        itemname = 'apple',
        label = 'apple',
        image = 'apple.png',
        count = 10, 
        category = 'item',
    },
    [5] = {
        itemname = 'beer',
        label = 'beer',
        image = 'beer.png',
        count = 10, 
        category = 'item',
    },
    [6] = {
        itemname = 'consumable_breakfast',
        label = 'consumable_breakfast',
        image = 'consumable_breakfast.png',
        count = 10, 
        category = 'item',
    },
    [7] = {
        itemname = 'consumable_fruitsalad',
        label = 'consumable_fruitsalad',
        image = 'consumable_fruitsalad.png',
        count = 10, 
        category = 'item',
    },
    [8] = {
        itemname = 'ammoarrownormal',
        label = 'ammoarrownormal',
        image = 'ammoarrownormal.png',
        count = 10, 
        category = 'item',
    },
    [9] = {
        itemname = 'campfire',
        label = 'campfire',
        image = 'campfire.png',
        count = 10, 
        category = 'item',
    },
    [10] = {
        itemname = 'ammorevolvernormal',
        label = 'ammorevolvernormal',
        image = 'ammorevolvernormal.png',
        count = 10, 
        category = 'item',
    },
    [11] = {
        itemname = 'consumable_meat_greavy',
        label = 'consumable_meat_greavy',
        image = 'consumable_meat_greavy.png',
        count = 10, 
        category = 'item',
    },
    [12] = {
        itemname = 'consumable_salmon',
        label = 'consumable_salmon',
        image = 'consumable_salmon.png',
        count = 10, 
        category = 'item',
    },
    [13] = {
        itemname = 'pet revive',
        label = 'pet revive',
        image = 'pet_revive.png',
        count = 10, 
        category = 'item',
    },
    [14] = {
        itemname = 'antipoison',
        label = 'antipoison',
        image = 'antipoison.png',
        count = 10, 
        category = 'item',
    },
    [15] = {
        itemname = 'lighter',
        label = 'lighter',
        image = 'lighter.png',
        count = 10, 
        category = 'item',
    },
    [16] = {
        itemname = 'orange juice',
        label = 'orange juice',
        image = 'orange juice.png',
        count = 10, 
        category = 'item',
    },
    [17] = {
        itemname = 'masks',
        label = 'masks',
        image = 'masks.png',
        count = 10, 
        category = 'item',
    },
    [18] = {
        itemname = 'sheild and spear accesory',
        label = 'sheild and spear accesory',
        image = 'sheild and spear accesory.png',
        count = 10, 
        category = 'item',
    },
    [19] = {
        itemname = 'pwace pipe',
        label = 'pwace pipe',
        image = 'pwace pipe.png',
        count = 10, 
        category = 'item',
    },
    [20] = {
        itemname = 'lockpick',
        label = 'lockpick',
        image = 'lockpick.png',
        count = 10, 
        category = 'item',
    },
    [21] = {
        itemname = 'guncloth',
        label = 'guncloth',
        image = 'guncloth.png',
        count = 10, 
        category = 'item',
    },
    [22] = {
        itemname = 'pomade',
        label = 'pomade',
        image = 'pomade.png',
        count = 10, 
        category = 'item',
    },
    [23] = {
        itemname = 'herbmed',
        label = 'herbmed',
        image = 'herbmed.png',
        count = 10, 
        category = 'item',
    },
    [24] = {
        itemname = 'syringe',
        label = 'syringe',
        image = 'syringe.png',
        count = 10, 
        category = 'item',
    },
    [25] = {
        itemname = 'journalist',
        label = 'journalist',
        image = 'journalist.png',
        count = 10, 
        category = 'item',
    },
    [26] = {
        itemname = 'consumable_veggies',
        label = 'consumable_veggies',
        image = 'consumable_veggies.png',
        count = 10, 
        category = 'item',
    },
    [27] = {
        itemname = 'morphine',
        label = 'morphine',
        image = 'morphine.png',
        count = 10, 
        category = 'item',
    },
    [28] = {
        itemname = 'vetsyringe',
        label = 'vetsyringe',
        image = 'vetsyringe.png',
        count = 10, 
        category = 'item',
    },
    [29] = {
        itemname = 'irobar',
        label = 'irobar',
        image = 'irobar.png',
        count = 10, 
        category = 'item',
    },
    [30] = {
        itemname = 'winerecipe',
        label = 'winerecipe',
        image = 'winerecipe.png',
        count = 10, 
        category = 'item',
    },
}
